site_name: packagename
nav:
  - Home: README.md
  - API: apidocs.md
  - Example: notebook-example.ipynb
  
theme:
  name: "material"
  icon:
    logo: material/clipboard
  features:
    - content.code.copy
    - content.code.annotate 
repo_url: https://github.com/pandoramission/pandora-blank
plugins:
  - search
  - include-markdown
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      watch:
        - src/packagename
      default_handler: python      
      handlers:
        python:
          options:
            show_source: false
            filters:
              - "!^_"
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
